version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    docker:
      - image: python
    steps:
      - checkout
      - run: python Main1.py

  test:
    docker:
      - image: python  # Fixed typo here
    steps:
      - checkout
      - run: python Test.py

# Orchestrate jobs using workflows
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build  # Ensure test job runs after build job
